runtime: nodejs16

# Optional: instance class and scaling settings
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

runtime: nodejs
env: flex
entrypoint: npm start

# Optional settings
manual_scaling:
  instances: 1
